//-*-c-*-
//=============================================================================
//
// Copyright (c) XXXX-XXXX
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

// This file should be auto generated by onnx2c.py,
// it's used as driver for testing ONNX.

#include <math.h>

#include "common/rtlib.h"

double Expected_data[] = {0.0, 0.0, 0.1259419, 0.9847309, 0.0,
                          0.0, 0.0, 0.56082,   0.0};
int    Expected_len    = 9;

/**
 * @brief generate input data for testing ONNX
 *
 *
 * @param n
 * @param c
 * @param h
 * @param w
 * @param data, data pointer
 * @return TENSOR input data
 */
TENSOR* Generate_input_data(size_t n, size_t c, size_t h, size_t w,
                            double* data) {
  return Alloc_tensor(n, c, h, w, data);
}

/**
 * @brief validate output vector with expect vector
 *
 *
 * @param result double *
 * @param expect double *
 * @param len int
 * @return return true if value match
 */
bool Validate_output_data(double* result, double* expect, int len) {
  double error = 1e-3;
  for (int i = 0; i < len; i++) {
    printf("index: %d, value: %f != %f\n", i, result[i], expect[i]);
    if (fabs(result[i] - expect[i]) > error) {
      return false;
    }
  }
  return true;
}

int main(int argc, char* argv[]) {
  Prepare_context();

  double input1[] = {
      -0.9099000096321106, -0.5096886157989502, 0.1259419023990631,
      0.984730863571167,   -0.2005770057439804, -0.4645185470581055,
      -0.9366079092025757, 0.5608199834823608,  -0.4445499181747437};
  TENSOR* input_data1 = Generate_input_data(1, 1, 3, 3, input1);
  printf("input");
  Print_tensor(stdout, input_data1);
  Prepare_input(input_data1, "input");
  Free_tensor(input_data1);

  Run_main_graph();

  double* result = Handle_output("output");

  Finalize_context();

  bool res = Validate_output_data(result, Expected_data, Expected_len);
  free(result);
  if (res) {
    printf("SUCESS!\n");
  } else {
    printf("FAILED!\n");
    return 1;
  }

  return 0;
}

// include fhe_cmplr generated eg_fhertlib_relu.inc
#include "eg_fhertlib_relu.inc"
