//-*-c-*-
//=============================================================================
//
// Copyright (c) XXXX-XXXX
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

// This file should be auto generated by onnx2c.py,
// it's used as driver for testing ONNX.

#include <math.h>

#include "common/rtlib.h"

double Expected_data[] = {-0.049736694, -0.083609276,  0.084969714,
                          0.05173664,   -0.0019556656, 0.052732594,
                          0.017478563,  0.05624237,    -0.06131136};
int    Expected_len    = 9;

/**
 * @brief generate input data for testing ONNX
 *
 *
 * @param n
 * @param c
 * @param h
 * @param w
 * @param data, data pointer
 * @return TENSOR input data
 */
TENSOR* Generate_input_data(size_t n, size_t c, size_t h, size_t w,
                            double* data) {
  return Alloc_tensor(n, c, h, w, data);
}

/**
 * @brief validate output vector with expect vector
 *
 *
 * @param result double *
 * @param expect double *
 * @param len int
 * @return return true if value match
 */
bool Validate_output_data(double* result, double* expect, int len) {
  double error = 1e-2;
  for (int i = 0; i < len; i++) {
    if (fabs(result[i] - expect[i]) > error) {
      printf("index: %d, value: %f != %f\n", i, result[i], expect[i]);
      return false;
    }
  }
  return true;
}

int main(int argc, char* argv[]) {
  Prepare_context();

  double input1[] = {
      -0.0431470051407814, -0.028020456433296204, 0.032034389674663544,
      0.09018663316965103, 0.06269433349370956,   0.003426089882850647,
      0.02059812843799591, 0.021943703293800354,  -0.007877632975578308};
  TENSOR* input_data1 = Generate_input_data(1, 1, 3, 3, input1);
  printf("input");
  Print_tensor(stdout, input_data1);
  Prepare_input(input_data1, "input");
  Free_tensor(input_data1);
  double input2[] = {
      -0.0065896883606910706, -0.055588819086551666, 0.05293532460927963,
      -0.03844999149441719,   -0.06464999914169312,  0.04930650442838669,
      -0.0031195655465126038, 0.03429866582155228,   -0.053433727473020554};
  TENSOR* input_data2 = Generate_input_data(1, 1, 3, 3, input2);
  printf("onnx::Add_1");
  Print_tensor(stdout, input_data2);
  Prepare_input(input_data2, "onnx::Add_1");
  Free_tensor(input_data2);

  Run_main_graph();

  double* result = Handle_output("output");

  Finalize_context();

  bool res = Validate_output_data(result, Expected_data, Expected_len);
  free(result);
  if (res) {
    printf("SUCCESS!\n");
  } else {
    printf("FAILED!\n");
    return 1;
  }

  return 0;
}

// include fhe-cmplr generated main_graph functions.
#include "eg_rtopenfhe_add.inc"
